### ISSUE TITLE
Knobs that are supposed to click don't

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#11]
I think this is a known VCV bug? I noticed it on Saws where the octave and semitone knobs are supposed to "click" to discrete values, but they don't.

**Comment by kockie69** [comment]
Yes, I have that problem with my Grendel module too. I will keep this one open and will check it if a new VCV versions are available

**Comment by squinkylabs** [comment]
I have seen some stuff on the community forum about this.

**Comment by kockie69** [comment]
All fixed now, where 2 modules that where suffering.
