### ISSUE TITLE
Build error log

### ISSUE THREAD

**Issue by Torinbob** [kockie69/SquinkyVCV-main#2]
Hi Robert,

Here is my build error log as discussed in case it is useful. (Marc tells me my build system is very pedantic haha so often throws up things that his doesn't)
[Squinky build log](https://github.com/kockie69/SquinkyVCV-main/files/7261352/Squinky.build.log)

**Comment by kockie69** [comment]
Others and myself have fixed a lot of the warnings. Would be good to see if the latest release has most of them removed for you.

**Comment by Torinbob** [comment]
Will try a pull and rebuild now and let you know.

**Comment by Torinbob** [comment]
it's a little better but still a lot of warnings - log is now 1816 lines rather than 2112

[squinky build log2.log](https://github.com/kockie69/SquinkyVCV-main/files/7269852/squinky.build.log2.log)
