### ISSUE TITLE
Here's a Mac build for 042a9ce0

### ISSUE THREAD

**Issue by Torinbob** [kockie69/SquinkyVCV-main#21]
Hi Robert,

Thanks again for all your work on this - here's a Mac build done with latest v2 beta 042a9ce0

[squinkylabs-plug1-2.0.2-mac.vcvplugin.zip](https://github.com/kockie69/SquinkyVCV-main/files/7271280/squinkylabs-plug1-2.0.2-mac.vcvplugin.zip)

**Comment by kockie69** [comment]
Great, thank you. I have added it to the release folder.
