### ISSUE TITLE
Solo buttons are missing from Form mixer

### ISSUE THREAD

**Issue by GrayCatMusic** [kockie69/SquinkyVCV-main#39]
<img width="913" alt="Screen Shot 2021-11-17 at 11 31 04 PM" src="https://user-images.githubusercontent.com/89216233/142357613-960dcca6-c15a-4503-92ed-8b26a91a94bd.png">

Everything else seems good though. This is for  v2.0.14 - Rack version 588342d7

**Comment by kockie69** [comment]
Is this on Linux or Mac? As I don't have this on Windows and have not yet been able to reproduce on Windows....

**Comment by GrayCatMusic** [comment]
This is on Mac

**Comment by kockie69** [comment]
Are you able to send me your log file? the one that is Documents/Rack2 ?

**Comment by kockie69** [comment]
I found the issue, no need to send me the log file. Apparently the Rack team has removed (on purpose?) some of the buttons that we are using. Because I did an update, and not a fresh reinstall the ' old'  file was still on my machine, but not on yours.

**Comment by GrayCatMusic** [comment]
Ahh ok. Sorry, I posted this right before I fell asleep last night otherwise I would have sent the log.

**Comment by kockie69** [comment]
You can build from master branch yourself or wait till release 2.0.15 becomes available.
