### ISSUE TITLE
SAWS: extremely hot output

### ISSUE THREAD

**Issue by Eurikon** [kockie69/SquinkyVCV-main#4]
Hi, i notice that the output on SAWS is extremely loud, don't remember if this was also in the 1.x version ?

edit: i just noticed this is only the case when the merged output of JW Modules NoteSeqFu is connected.

hmmm, puzzling

**Comment by kockie69** [comment]
Are you able to check on v1 too for me please? I want to keep the 'normal' bugs separate from the V2 porting ones. Also, I am not an expert on the behaviour of the modules so any help on that is appreciated.

**Comment by Eurikon** [comment]
Hi Robert, 
i checked in V1, same behaviour. 

Seem to be the stacking of the polyphonic voices. 
I don't get why the doubling of gain is so over exaggerated, but apparently it has been like this always. 

I'll check with Bruce and Jeremy, if they know something about this.

Thanks for the port to V2! :)

**Comment by kockie69** [comment]
I will close the issue for now , you can reopen it if you think it is a bug.
