### ISSUE TITLE
permission to submit to library

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#40]
Looks like they want an email giving you permission to submit these modules to the library. I assume you want to do that, so I figure I'll send a mail giving your gmail and a link to the repo?

**Comment by kockie69** [comment]
Yes that is fine with me. Looks like they are planning to release soon.

**Comment by squinkylabs** [comment]
ok, I cc'd you on the email. Now I think you need to actually submit these: https://community.vcvrack.com/t/now-taking-submissions-of-v2-plugins-to-the-library/14747

**Comment by kockie69** [comment]
Thank you, I also saw your email. I have submitted a request so let's see what happens.
