### ISSUE TITLE
Last version seems doesn't get any input signal to the output

### ISSUE THREAD

**Issue by vcvrackideas** [kockie69/SquinkyVCV-main#41]
Hi! Just tested Shaper with latest RackSDK2 and it passes no signal through it. When I compiled that I saw many times error something about wrong bypass route. Cheers

**Comment by kockie69** [comment]
Hi, thank you for finding this one. It is not related to the warnings (not errors) but was caused by some change I had done in the past but only reversed half. 
If you build from latest commit shaper should work again.
