### ISSUE TITLE
elimination of link time optimization will slow things down a little

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#5]
These flags did make a noticeable difference in the efficiency of Kitchen Sink on windows. I don't know if I checked it in turned off or you did.

#  -flto
# FLAGS += -finline-limit=500000 -finline-functions-called-once -flto
# LDFLAGS += -flto
FLAGS +=
LDFLAGS +=

**Comment by kockie69** [comment]
Linker error was caused by -O0 in compiler. By switching back to the standard -O3 this was fixed.

**Comment by squinkylabs** [comment]
ah! I must have checked in some debugging code by mistake. thanks!
