### ISSUE TITLE
Comp II mutes when in bypass mode

### ISSUE THREAD

**Issue by Petervos2018** [kockie69/SquinkyVCV-main#53]
As seen in :  

https://community.vcvrack.com/t/bypass-cutting-signal-in-v2/15042/7?u=yeager

Was joking about a list.

Greetings Peter.

**Comment by kockie69** [comment]
Yes, you where completely right. For some reason I missed this one. I have added the new bypass code and it will be available in the next release. By the way, this module has a bypass button , so you could have used that option ;-)

**Comment by kockie69** [comment]
You can download a test release here:

https://github.com/kockie69/SquinkyVCV-main/releases/tag/v2.1.3

**Comment by Petervos2018** [comment]
Works !
Thank you.
