### ISSUE TITLE
seq++ not saving/duplicating note seq in v2.0.2

### ISSUE THREAD

**Issue by muttlee23** [kockie69/SquinkyVCV-main#54]
howdy!

the seq++ is not saving the note seq in v2.0.2

duplicating the module and saving/loading a preset is also not storing the note seq

thanks for pickup the great stuff squinky labs moved on from.  it's greatly appreachated!

cheers

**Comment by kockie69** [comment]
For some reason the code to load the seq++ data was commented out by myself. Fixed, and I have uploaded the latest version to VCV. As soon as they have processed it, it should be available in the 2.1.3 release.

**Comment by muttlee23** [comment]
thanks for fixing it so quickly!
