### ISSUE TITLE
Seq++ Does not recall midi files when reopening patch in VCV Rack 2

### ISSUE THREAD

**Issue by jaffasplaffa** [kockie69/SquinkyVCV-main#55]
Hey :) 

Been playing around the seq++ for playing midi files, it's a pretty cool module.

But when I use it in VCV Rack 2 Free, Seq++ does not recall the midi file I've loaded into it.

Just thought I'd let you know.

**Comment by kockie69** [comment]
There is an 2.1.3 update provided to the VCV team that should be deployed very soon. This contains the fix, which was already raised by someone else this morning.
