### ISSUE TITLE
up down value changers are hard to use

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#56]
There are many types up "value selectors" in VCV. The ones in Pigeon Plink are difficult to use because you can't see what the possible values are, and the buttons for up and down are very small and non-intuitive. Hopefull they still can be controlled with the midi mapper.

Contrary to claim, Vult does not use the value selectors, they usually use a slide switch (as so some Squinky labs modules).
![image](https://user-images.githubusercontent.com/16314838/149820880-a9d9199d-463e-4cc5-b234-17fa27beca9f.png)

**Comment by squinkylabs** [comment]
oops, this issue should have been opened in the other repo.

**Comment by kockie69** [comment]
Close this one as we have it in the RPJ repo now
