### ISSUE TITLE
tooltips in 4X4 are wir

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#6]
![image](https://user-images.githubusercontent.com/16314838/135545142-4e89604d-4e22-40e4-befb-1dead91ad7d8.png)

I already implement my own port tooltips on 4X4. Maybe that's why these are messed up? I don't know. When I suggested port tooltips to VCV a couple of years ago I was told it was a bad idea. oh well.

**Comment by kockie69** [comment]
I have removed the tooltips so now it is standard VCV. I will add a new task to add the original tooltip texts back in

**Comment by squinkylabs** [comment]
good decision. fwiw I think this is the only module that did this, and I did it because it was not obvious what some of those multi-function jacks did.
