### ISSUE TITLE
No arm64 ...

### ISSUE THREAD

**Issue by jackokring** [kockie69/SquinkyVCV-main#79]
SSE? MMX? AVX?

**Comment by kockie69** [comment]
Sorry, what is it that you want?

**Comment by jackokring** [comment]
Just noting that it "doesn't compile" on a `lin-arm64` due to likely intrinsic architecture specific instructions. I don't expect it to compile in the future as it is very tightly architecture coupled code. It's an issue that it doesn't. Not necessarily an issue that can be solved or even should be. Nice modules by the way.

I've no interest myself in the `mac-arm64` beta test. ...

**Comment by davephillips** [comment]
@kockie69 - I'm very interested in any plan to have Squinky Labs on native arm64. It looks like it might be a big job, just wondered if it's on the roadmap.

**Comment by kockie69** [comment]
It is already done. Bacon Paul provided me the details.  But I have had no
time yet to do any release. Will be available for download tomorrow or day
after I hope.

**Comment by kockie69** [comment]
I have mad an arm build. Also latest commit can be used for building your own if you want. You can grab a build from here:

https://drive.google.com/drive/folders/18--sydW2ilyhVn_cnycXb46GYzxWSMLB?usp=sharing
