### ISSUE TITLE
Please consider changing the license to GPLv3+ (GNU General Public License v3.0 or later)

### ISSUE THREAD

**Issue by GBaige** [kockie69/SquinkyVCV-main#81]
It's not a simple request, I know, but it would make it possible to finally include these modules in Cardinal, which only allows GPLv3+ modules...

**Comment by cmorse01** [comment]
I'd like to second this request.  I don't know the nuances of 3.0-only vs 3.0+, but I also use Cardinal/Carla combo and would really love the option to see the quality squinky modules brought into Cardinal.  Particularly Organ-Three...

**Comment by GBaige** [comment]
I absolutely love Squinky's filters. No other module dev so far has been able to, for instance, create an alternative to its formant filter except Autodafe, but the latter's modules aren't even open-source to my knowledge.

**Comment by GBaige** [comment]
I've just realized that the current maintainer simply ported the modules to the 2.0 format but may not even own the modules. It could be up to the original developers themselves to change the license, and chances of that happening are slim to none. I'll still keep the issue open in case someone else wants to chime in or the maintainer replies.

**Comment by kockie69** [comment]
I am now the owner of these modules but at the moment not interested in spending any energy in supporting Cardinal.

**Comment by GBaige** [comment]
> I am now the owner of these modules but at the moment not interested in spending any time or energy in supporting Cardinal.

You don't have to. All we'd need is the license to change to GPLv3-or-later and someone else can port the modules to Cardinal, just like with every other GPLv3-or-later module that was ported to Cardinal. But it sounds like you won't even do that, so I'll just close this issue. Sorry for wasting your time.
