### ISSUE TITLE
the new blue knobs are a different color than the old ones

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#9]
Once could certainly argue that the new color looks better, but the old color is used for a lot of other controls and drawing, so ideally these would all be the same.

![image](https://user-images.githubusercontent.com/16314838/135546350-68dda50d-f53d-4e55-b370-f0a5d2712cc3.png)

**Comment by kockie69** [comment]
All the blue knobs now have the old blue again. Created my own knobs in Squinky Blue
