### ISSUE TITLE
seq++ playhead not visible

### ISSUE THREAD

**Issue by giohappy** [kockie69/SquinkyVCV-main#90]
I don't know if I'm making something wrong but I can't see the playhead while seq++ is playing.
Gate and V/Oct are outputting the expected values when running, but I only see the blinking edit cursor

![seq++ playhead](https://github.com/kockie69/SquinkyVCV-main/assets/571129/6cea5108-68d6-4f6f-b43a-cc8407ae81fa)

**Comment by Petervos2018** [comment]
As I said in the forum : Activate the SCROLL button (on Seq++).
